---
- hosts: all
  sudo: yes
  tasks:
    - name: Add Docker Key
      command: apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

    - name: Add Docker Repo
      apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present

    - name: Install Docker package
      apt: "pkg=docker-engine state=latest force=true"

    - name: Add Docker group
      group: name=docker state=present

    - name: Add vagrant user to docker group
      user: name=vagrant groups=docker append=yes

    - name: Adjust Docker defaults
      lineinfile: >
        dest=/etc/default/docker
        line='DOCKER_OPTS="-H tcp://192.168.1.10:2376 -H unix:///var/run/docker.sock"'
        regexp='^DOCKER_OPTS'

    - name: Restart Docker
      service: name=docker enabled=true state=restarted
