---
- hosts: all
  vars:
    docker_version: 1.3.1
  sudo: yes
  tasks:
    - name: Add Docker Key
      command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9

    - name: Add Docker Repo
      apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present

    - name: Install Docker package
      apt: "pkg=lxc-docker-{{ docker_version }} state=present force=true"

    - name: Add Docker group
      group: name=docker state=present

    - name: Add vagrant user to docker group
      user: name=vagrant groups=docker append=yes

    - name: Adjust Docker defaults
      lineinfile: >
        dest=/etc/default/docker
        line='DOCKER_OPTS="-H tcp://192.168.5.10:2375 "'
        regexp='^DOCKER_OPTS'
      notify: Restart Docker

  handlers:
    - name: Restart Docker
      service: name=docker enabled=true state=restarted
